Models/Avtor.cs
using System.ComponentModel.DataAnnotations;

namespace Knigi.Models
{
    public class Avtor
    { 
        public int Id { get; set; }

        [StringLength(50)]
        public string? Ime { get; set; }

        [StringLength(50)]
        public string? Prezime { get; set; }

        public string FullName
        {
            get { return string.Format("{0} {1}", Ime, Prezime); }
        }

        [StringLength(50)]
        public string? Nacionalnost { get; set; }

        [Display(Name = "Daturm na ragjanje")]
        [DataType(DataType.Date)]
        public DateTime DatumRagjanje { get; set; }

        public ICollection<Kniga>? Knigi { get; set; }
    }
}

Controllers/AvtorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Knigi.Data;
using Knigi.Models;

namespace Knigi.Controllers
{
    public class AvtorsController : Controller
    {
        private readonly KnigiContext _context;

        public AvtorsController(KnigiContext context)
        {
            _context = context;
        }

        // GET: Avtors
        public async Task<IActionResult> Index()
        {
              return _context.Avtor != null ? 
                          View(await _context.Avtor.ToListAsync()) :
                          Problem("Entity set 'KnigiContext.Avtor'  is null.");
        }

        // GET: Avtors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Avtor == null)
            {
                return NotFound();
            }

            var avtor = await _context.Avtor
                .FirstOrDefaultAsync(m => m.Id == id);
            if (avtor == null)
            {
                return NotFound();
            }

            return View(avtor);
        }

        // GET: Avtors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Avtors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Ime,Prezime,Nacionalnost,DatumRagjanje")] Avtor avtor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(avtor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(avtor);
        }

        // GET: Avtors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Avtor == null)
            {
                return NotFound();
            }

            var avtor = await _context.Avtor.FindAsync(id);
            if (avtor == null)
            {
                return NotFound();
            }
            return View(avtor);
        }

        // POST: Avtors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Ime,Prezime,Nacionalnost,DatumRagjanje")] Avtor avtor)
        {
            if (id != avtor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(avtor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AvtorExists(avtor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(avtor);
        }

        // GET: Avtors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Avtor == null)
            {
                return NotFound();
            }

            var avtor = await _context.Avtor
                .FirstOrDefaultAsync(m => m.Id == id);
            if (avtor == null)
            {
                return NotFound();
            }

            return View(avtor);
        }

        // POST: Avtors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Avtor == null)
            {
                return Problem("Entity set 'KnigiContext.Avtor'  is null.");
            }
            var avtor = await _context.Avtor.FindAsync(id);
            if (avtor != null)
            {
                _context.Avtor.Remove(avtor);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AvtorExists(int id)
        {
          return (_context.Avtor?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/KnigasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Knigi.Data;
using Knigi.Models;
using Knigi.ViewModels;

namespace Knigi.Controllers
{
    public class KnigasController : Controller
    {
        private readonly KnigiContext _context;

        public KnigasController(KnigiContext context)
        {
            _context = context;
        }

        // GET: Knigas
        public async Task<IActionResult> Index(string searchNaslov, string searchAvtor, string searchGodina, string knigaZanr)
        {
            IQueryable<Kniga> knigi = _context.Kniga.AsQueryable();
            IQueryable<string> zanrQuery = _context.Zanr.Select(x => x.Ime);


            if(!string.IsNullOrEmpty(searchNaslov))
            {
                knigi = knigi.Where(x => x.Naslov.Contains(searchNaslov));
            }

            if(!string.IsNullOrEmpty(searchAvtor))
            {
                knigi = knigi.Where(x => x.Avtor.Ime.Contains(searchAvtor) || x.Avtor.Prezime.Contains(searchAvtor));
            }

            if(!string.IsNullOrEmpty(searchGodina))
            {
                knigi = knigi.Where(x => x.Godina.ToString() == searchGodina);
            }

            if(!string.IsNullOrEmpty(knigaZanr))
            {
                knigi = knigi.Where(x => x.Zanrovi.Any(x => x.Zanr.Ime == knigaZanr));
            }

            knigi = knigi.Include(x => x.Avtor).Include(x => x.Zanrovi!).ThenInclude(x => x.Zanr);

            var knigaFilterVM = new KnigaFilterViewModel
            {
                Knigi = await knigi.ToListAsync(),
                Zanrovi = new SelectList(await zanrQuery.ToListAsync())
            };

            return View(knigaFilterVM);
        }

        // GET: Knigas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Kniga == null)
            {
                return NotFound();
            }

            var kniga = await _context.Kniga
                .Include(k => k.Avtor)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (kniga == null)
            {
                return NotFound();
            }

            return View(kniga);
        }

        // GET: Knigas/Create
        public IActionResult Create()
        {
            var zanrovi = _context.Zanr.ToList();

            var viewModel = new KnigaCreateViewModel
            { 
                Kniga = new Kniga(),
                ZanroviLista = zanrovi.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Ime
                })
            };

            ViewData["AvtorId"] = new SelectList(_context.Avtor, "Id", "FullName");
            return View(viewModel);
        }

        // POST: Knigas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(KnigaCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(viewModel.Kniga);
                await _context.SaveChangesAsync();

                if (viewModel.SelectedZanrovi != null)
                {
                    foreach (var zanrId in viewModel.SelectedZanrovi)
                    {
                        var knigaZanr = new KnigaZanr
                        {
                            KnigaId = viewModel.Kniga.Id,
                            ZanrId = zanrId
                        };
                        _context.Add(knigaZanr);
                    }
                }

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AvtorId"] = new SelectList(_context.Avtor, "Id", "FullName", viewModel.Kniga.AvtorId);
            viewModel.ZanroviLista = _context.Zanr.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Ime
            });
            return View(viewModel.Kniga);
        }

        // GET: Knigas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Kniga == null)
            {
                return NotFound();
            }

            var kniga = _context.Kniga.Where(x => x.Id == id).Include(x => x.Zanrovi).First();
            if (kniga == null)
            {
                return NotFound();
            }

            var zanrovi = _context.Zanr.AsEnumerable();

            var knigaEditVM = new KnigaEditViewModel
            {
                Kniga = kniga,
                ZanrLista = new MultiSelectList(zanrovi, "Id", "Ime"),
                SelektiraniZanrovi = kniga.Zanrovi.Select(x => x.ZanrId)
            };

            ViewData["AvtorId"] = new SelectList(_context.Avtor, "Id", "FullName", kniga.AvtorId);
            return View(knigaEditVM);
        }

        // POST: Knigas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, KnigaEditViewModel viewModel)
        {
            if (id != viewModel.Kniga.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(viewModel.Kniga);
                    await _context.SaveChangesAsync();

                    IEnumerable<int> novaZanrLista = viewModel.SelektiraniZanrovi!;
                    IEnumerable<int> prethodnaZanrLista = _context.KnigaZanr.Where(x => x.KnigaId == id).Select(x => x.ZanrId);
                    IQueryable<KnigaZanr> toBeRemoved = _context.KnigaZanr.Where(x => x.KnigaId == id);

                    if(novaZanrLista != null)
                    {
                        toBeRemoved = toBeRemoved.Where(x => novaZanrLista.Contains(x.ZanrId));
                        foreach (int zanrId in novaZanrLista)
                        {
                            if(!prethodnaZanrLista.Any(x => x == zanrId))
                            {
                                _context.KnigaZanr.Add(new KnigaZanr { ZanrId = zanrId, KnigaId = id });
                            }
                        }
                    }

                    _context.KnigaZanr.RemoveRange(toBeRemoved);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KnigaExists(viewModel.Kniga.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AvtorId"] = new SelectList(_context.Avtor, "Id", "FullName", viewModel.Kniga.AvtorId);
            return View(viewModel.Kniga);
        }

        // GET: Knigas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Kniga == null)
            {
                return NotFound();
            }

            var kniga = await _context.Kniga
                .Include(k => k.Avtor)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (kniga == null)
            {
                return NotFound();
            }

            return View(kniga);
        }

        // POST: Knigas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Kniga == null)
            {
                return Problem("Entity set 'KnigiContext.Kniga'  is null.");
            }
            var kniga = await _context.Kniga.FindAsync(id);
            if (kniga != null)
            {
                _context.Kniga.Remove(kniga);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KnigaExists(int id)
        {
          return (_context.Kniga?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Avtors/Create.cshtml
@model Knigi.Models.Avtor

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Avtor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Ime" class="control-label"></label>
                <input asp-for="Ime" class="form-control" />
                <span asp-validation-for="Ime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prezime" class="control-label"></label>
                <input asp-for="Prezime" class="form-control" />
                <span asp-validation-for="Prezime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nacionalnost" class="control-label"></label>
                <input asp-for="Nacionalnost" class="form-control" />
                <span asp-validation-for="Nacionalnost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatumRagjanje" class="control-label"></label>
                <input asp-for="DatumRagjanje" class="form-control" />
                <span asp-validation-for="DatumRagjanje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Avtors/Delete.cshtml
@model Knigi.Models.Avtor

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Avtor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prezime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prezime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nacionalnost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nacionalnost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatumRagjanje)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatumRagjanje)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Avtors/Details.cshtml
@model Knigi.Models.Avtor

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Avtor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prezime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prezime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nacionalnost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nacionalnost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatumRagjanje)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatumRagjanje)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Avtors/Edit.cshtml
@model Knigi.Models.Avtor

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Avtor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Ime" class="control-label"></label>
                <input asp-for="Ime" class="form-control" />
                <span asp-validation-for="Ime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prezime" class="control-label"></label>
                <input asp-for="Prezime" class="form-control" />
                <span asp-validation-for="Prezime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nacionalnost" class="control-label"></label>
                <input asp-for="Nacionalnost" class="form-control" />
                <span asp-validation-for="Nacionalnost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatumRagjanje" class="control-label"></label>
                <input asp-for="DatumRagjanje" class="form-control" />
                <span asp-validation-for="DatumRagjanje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Avtors/Index.cshtml
@model IEnumerable<Knigi.Models.Avtor>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nacionalnost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatumRagjanje)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @*@Html.DisplayFor(modelItem => item.FullName)*@
                <a href="@Url.Action("Index", "Knigas", new { SearchAvtor = item.Prezime })">
                    @Html.DisplayFor(modelItem => item.FullName)
                </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nacionalnost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatumRagjanje)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>